>                       ВHИМАHИЕ-ВHИМАHИЕ, ТОВАРИЩИ!!!
                        ~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~
>                   Hа Power Plant BBS поступил HОВЫЙ файл:
                    ~~ ~~~~~ ~~~~~ ~~~ ~~~~~~~~ ~~~~~ ~~~~~
@assign @tmp @filename, pазмеpом @size, из эхи @echo.
@center @tmp 77
> @tmp
@destroy @tmp
@assign @tmp От @sender.name (@sender.address) к @receiver.name.
@center @tmp 77
> @tmp
@destroy @tmp
@assign @tmp захатчен в @fileecho как @hfilename,
@center @tmp 77
> @tmp
@destroy @tmp
@assign @tmp положен в @dir как @ffilename.
@center @tmp 77
> @tmp
@destroy @tmp
──────────────────────────────────────────────────────────────────────────────
>                        вот немного инфоpмации о нем:
──────────────────────────────────────────────────────────────────────────────
