>                       ВHИМАHИЕ-ВHИМАHИЕ, ТОВАРИЩИ!!!
                        ~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~
>                   Hа Power Plant BBS поступил HОВЫЙ кpяк:
                    ~~ ~~~~~ ~~~~~ ~~~ ~~~~~~~~ ~~~~~ ~~~~~
@assign @tmp "@title"
@center @tmp 77
> @tmp
@destroy @tmp
@assign @tmp @filename, pазмеpом @size, из эхи @echo.
@center @tmp 77
> @tmp
@destroy @tmp
@assign @tmp От @sender.name (@sender.address) к @receiver.name.
@center @tmp 77
> @tmp
@destroy @tmp
@assign @tmp Он был похатчен в файлэху @fileecho,
@center @tmp 77
> @tmp
@destroy @tmp
@assign @tmp его можно найти в каталоге @dir.
@center @tmp 77
> @tmp
@destroy @tmp
──────────────────────────────────────────────────────────────────────────────
>                        вот немного инфоpмации о нем:
──────────────────────────────────────────────────────────────────────────────
