วฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤลฤฤฤฤฤฤฤฤฤลฤฤฤฤฤฤฤฤฤลฤฤฤฤฤฤฤฤฤลฤฤฤยฤฤฤฤฤฤฤฤฤฤฤฤฤถ
@convsize @netmail 7
@leftpad @netmail 7
@convsize @arcmail 7
@leftpad @arcmail 7
@convsize @files 7
@leftpad @files 7
@assign @foot Total: @nodes nodes
@pad @foot 27
บ @foot ณ @netmail ณ @arcmail ณ @files ณ M ณ netmail     บ
บ                             รฤฤฤฤฤฤฤฤฤมฤฤฤฤฤฤฤฤฤมฤฤฤฤฤฤฤฤฤด A ณ arcmail     บ
@convsize @total 27
@center @total 27
บ                             ณ @total ณ F ณ files       บ
ศอออออออออออออออออออออออออออออฯอออออออออออออออออออออออออออออฯอออฯอออออออออออออผ
@destroy @foot

--- Binkley Statistics Plugin created by sergey korowkin, 1998-99.
