
@assign @title Created at @curhour:@curmin, @curday/@curmonth/@curyear by BinkSTAT for FastUUE (c) sk, 1998-99.
@pad @title 75
ษอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
บ @title บ
วฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤยฤฤฤฤฤฤฤฤฤยฤฤฤฤฤฤฤฤฤยฤฤฤฤฤฤฤฤฤยฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤถ
บ Address                     ณ NetMail ณ ArcMail ณ  Files  ณ   Flavour map   บ
วฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤลฤฤฤฤฤฤฤฤฤลฤฤฤฤฤฤฤฤฤลฤฤฤฤฤฤฤฤฤลฤฺIฟฺCฟฺDฟฺNฟฺHฟฤถ
@destroy @title